require __dir__ + '/../utils/fonticon/IconsFontAwesome6'

#$IconFontsTbl = [\
#  ICON_FA_0 + " ICON_FA_0" ,
#  ICON_FA_1 + " ICON_FA_2" ,
#  ICON_FA_ADDRESS_BOOK + " ICON_FA_ADDRESS_BOOK",
#]

sOut = <<EOF
# DON'T EDIT THIS FILE
# This file is auto generated by "ruby makeIconFontsTblDef.rb"
EOF
sOut += "\nrequire __dir__ +  '/../utils/fonticon/IconsFontAwesome6'\n\n"
sOut += "$IconFontsTbl = [\\"

File.open("../utils/fonticon/IconsFontAwesome6.rb", mode="rt"){|fp|
  fp.each_line{|line|
    if line =~ /.+(ICON_FA.+)\s=\s(.+)/ then
       sOut += "\n  #{$1} + \" #{$1}\" , "
    end
  }
}
sOut +=  "\n]"

File.open("iconFontsTblDef.rb", mode = "w"){|fp|
  fp.write(sOut)
}
