ICON_EXE       = res/r.ico
ICON_TITLE_BAR = res/r.png

ADDED_FILES += $(ICON_EXE) $(ICON_TITLE_BAR)

#OPT += --debug-extract
#OPT += --debug
OPT += --windows
OPT += --icon $(ICON_EXE)
#OPT += --no-lzma

include ../makefile.common.mk
