# This file has been auto generated by srcript, see genImSpinnerRubyFFI.rb


#
#  The MIT License (MIT)

#  Copyright (c) 2025 dinau

#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:

#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.

#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.
#

require_relative '../utils/dll_path'

require 'ffi'
module ImGui
  extend FFI::Library
  ffi_lib get_imgui_dll_path()

# [  1] C++ definition
#     void Spinner::SpinnerRainbow(const char *label, float radius, float thickness, const ImColor &color, float speed, float ang_min = 0.f, float ang_max = PI_2, int arcs = 1, int mode = 0)
  attach_function :SpinnerRainbow,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerRainbowEx, [:string, :float, :float, :pointer, :float, :float, :float, :int, :int], :void

# [  2] C++ definition
#     void Spinner::SpinnerRainbowMix(const char *label, float radius, float thickness, const ImColor &color, float speed, float ang_min = 0.f, float ang_max = PI_2, int arcs = 1, int mode = 0)
  attach_function :SpinnerRainbowMix,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerRainbowMixEx, [:string, :float, :float, :pointer, :float, :float, :float, :int, :int], :void

# [  3] C++ definition
#     void Spinner::SpinnerRotatingHeart(const char *label, float radius, float thickness, const ImColor &color, float speed, float ang_min = 0.f)
  attach_function :SpinnerRotatingHeart,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerRotatingHeartEx, [:string, :float, :float, :pointer, :float, :float], :void

# [  4] C++ definition
#     void Spinner::SpinnerAng(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = white, float speed = 2.8f, float angle = IM_PI, int mode = 0)
  attach_function :SpinnerAng,   [:string, :float, :float], :void
  attach_function :SpinnerAngEx, [:string, :float, :float, :pointer, :pointer, :float, :float, :int], :void

# [  5] C++ definition
#     void Spinner::SpinnerAng8(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = white, float speed = 2.8f, float angle = IM_PI, int mode = 0, float rkoef = 0.5f)
  attach_function :SpinnerAng8,   [:string, :float, :float], :void
  attach_function :SpinnerAng8Ex, [:string, :float, :float, :pointer, :pointer, :float, :float, :int, :float], :void

# [  6] C++ definition
#     void Spinner::SpinnerAngMix(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, float angle = IM_PI, int arcs = 4, int mode = 0)
  attach_function :SpinnerAngMix,   [:string, :float, :float], :void
  attach_function :SpinnerAngMixEx, [:string, :float, :float, :pointer, :float, :float, :int, :int], :void

# [  7] C++ definition
#     void Spinner::SpinnerLoadingRing(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = half_white, float speed = 2.8f, int segments = 5)
  attach_function :SpinnerLoadingRing,   [:string, :float, :float], :void
  attach_function :SpinnerLoadingRingEx, [:string, :float, :float, :pointer, :pointer, :float, :int], :void

# [  8] C++ definition
#     void Spinner::SpinnerClock(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = half_white, float speed = 2.8f)
  attach_function :SpinnerClock,   [:string, :float, :float], :void
  attach_function :SpinnerClockEx, [:string, :float, :float, :pointer, :pointer, :float], :void

# [  9] C++ definition
#     void Spinner::SpinnerPulsar(const char *label, float radius, float thickness, const ImColor &bg = half_white, float speed = 2.8f, bool sequence = true, float angle = 0.f, int mode = 0)
  attach_function :SpinnerPulsar,   [:string, :float, :float], :void
  attach_function :SpinnerPulsarEx, [:string, :float, :float, :pointer, :float, :bool, :float, :int], :void

# [ 10] C++ definition
#     void Spinner::SpinnerDoubleFadePulsar(const char *label, float radius, float thickness, const ImColor &bg = half_white, float speed = 2.8f)
  attach_function :SpinnerDoubleFadePulsar,   [:string, :float, :float], :void
  attach_function :SpinnerDoubleFadePulsarEx, [:string, :float, :float, :pointer, :float], :void

# [ 11] C++ definition
#     void Spinner::SpinnerTwinPulsar(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int rings = 2, int mode = 0)
  attach_function :SpinnerTwinPulsar,   [:string, :float, :float], :void
  attach_function :SpinnerTwinPulsarEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 12] C++ definition
#     void Spinner::SpinnerFadePulsar(const char *label, float radius, const ImColor &color = white, float speed = 2.8f, int rings = 2, int mode = 0)
  attach_function :SpinnerFadePulsar,   [:string, :float], :void
  attach_function :SpinnerFadePulsarEx, [:string, :float, :pointer, :float, :int, :int], :void

# [ 13] C++ definition
#     void Spinner::SpinnerFadePulsarSquare(const char *label, float radius, const ImColor &color = white, float speed = 2.8f, int rings = 2, int mode = 0)
  attach_function :SpinnerFadePulsarSquare,   [:string, :float], :void
  attach_function :SpinnerFadePulsarSquareEx, [:string, :float, :pointer, :float, :int, :int], :void

# [ 14] C++ definition
#     void Spinner::SpinnerCircularLines(const char *label, float radius, const ImColor &color = white, float speed = 1.8f, int lines = 8, int mode = 0)
  attach_function :SpinnerCircularLines,   [:string, :float], :void
  attach_function :SpinnerCircularLinesEx, [:string, :float, :pointer, :float, :int, :int], :void

# [ 15] C++ definition
#     void Spinner::SpinnerDots(const char *label, float *nextdot, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 12, float minth = -1.f, int mode = 0)
  attach_function :SpinnerDots,   [:string, :pointer, :float, :float], :void
  attach_function :SpinnerDotsEx, [:string, :pointer, :float, :float, :pointer, :float, :int, :float, :int], :void

# [ 16] C++ definition
#     void Spinner::SpinnerVDots(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bgcolor = white, float speed = 2.8f, size_t dots = 12, size_t mdots = 6, int mode = 0)
  attach_function :SpinnerVDots,   [:string, :float, :float], :void
  attach_function :SpinnerVDotsEx, [:string, :float, :float, :pointer, :pointer, :float, :int, :int, :int], :void

# [ 17] C++ definition
#     void Spinner::SpinnerBounceDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 3, int mode = 0)
  attach_function :SpinnerBounceDots,   [:string, :float, :float], :void
  attach_function :SpinnerBounceDotsEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 18] C++ definition
#     void Spinner::SpinnerZipDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 5)
  attach_function :SpinnerZipDots,   [:string, :float, :float], :void
  attach_function :SpinnerZipDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 19] C++ definition
#     void Spinner::SpinnerDotsToPoints(const char *label, float radius, float thickness, float offset_k, const ImColor &color = white, float speed = 1.8f, size_t dots = 5)
  attach_function :SpinnerDotsToPoints,   [:string, :float, :float, :float], :void
  attach_function :SpinnerDotsToPointsEx, [:string, :float, :float, :float, :pointer, :float, :int], :void

# [ 20] C++ definition
#     void Spinner::SpinnerDotsToBar(const char *label, float radius, float thickness, float offset_k, const ImColor &color = white, float speed = 2.8f, size_t dots = 5)
  attach_function :SpinnerDotsToBar,   [:string, :float, :float, :float], :void
  attach_function :SpinnerDotsToBarEx, [:string, :float, :float, :float, :pointer, :float, :int], :void

# [ 21] C++ definition
#     void Spinner::SpinnerWaveDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8)
  attach_function :SpinnerWaveDots,   [:string, :float, :float], :void
  attach_function :SpinnerWaveDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 22] C++ definition
#     void Spinner::SpinnerFadeDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8, int mode = 0)
  attach_function :SpinnerFadeDots,   [:string, :float, :float], :void
  attach_function :SpinnerFadeDotsEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 23] C++ definition
#     void Spinner::SpinnerThreeDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8)
  attach_function :SpinnerThreeDots,   [:string, :float, :float], :void
  attach_function :SpinnerThreeDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 24] C++ definition
#     void Spinner::SpinnerFiveDots(const char *label, float radius, float thickness, const ImColor &color = 0xffffffff, float speed = 2.8f, int lt = 8)
  attach_function :SpinnerFiveDots,   [:string, :float, :float], :void
  attach_function :SpinnerFiveDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 25] C++ definition
#     void Spinner::Spinner4Caleidospcope(const char *label, float radius, float thickness, const ImColor &color = 0xffffffff, float speed = 2.8f, int lt = 8)
  attach_function :Spinner4Caleidospcope,   [:string, :float, :float], :void
  attach_function :Spinner4CaleidospcopeEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 26] C++ definition
#     void Spinner::SpinnerMultiFadeDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8)
  attach_function :SpinnerMultiFadeDots,   [:string, :float, :float], :void
  attach_function :SpinnerMultiFadeDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 27] C++ definition
#     void Spinner::SpinnerThickToSin(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int nt = 1, int lt = 8, int mode = 0)
  attach_function :SpinnerThickToSin,   [:string, :float, :float], :void
  attach_function :SpinnerThickToSinEx, [:string, :float, :float, :pointer, :float, :int, :int, :int], :void

# [ 28] C++ definition
#     void Spinner::SpinnerScaleDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8)
  attach_function :SpinnerScaleDots,   [:string, :float, :float], :void
  attach_function :SpinnerScaleDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 29] C++ definition
#     void Spinner::SpinnerSquareSpins(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerSquareSpins,   [:string, :float, :float], :void
  attach_function :SpinnerSquareSpinsEx, [:string, :float, :float, :pointer, :float], :void

# [ 30] C++ definition
#     void Spinner::SpinnerMovingDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 3)
  attach_function :SpinnerMovingDots,   [:string, :float, :float], :void
  attach_function :SpinnerMovingDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 31] C++ definition
#     void Spinner::SpinnerRotateDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int dots = 2, int mode = 0)
  attach_function :SpinnerRotateDots,   [:string, :float, :float], :void
  attach_function :SpinnerRotateDotsEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 32] C++ definition
#     void Spinner::SpinnerOrionDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int arcs = 4)
  attach_function :SpinnerOrionDots,   [:string, :float, :float], :void
  attach_function :SpinnerOrionDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 33] C++ definition
#     void Spinner::SpinnerGalaxyDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int arcs = 4)
  attach_function :SpinnerGalaxyDots,   [:string, :float, :float], :void
  attach_function :SpinnerGalaxyDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 34] C++ definition
#     void Spinner::SpinnerTwinAng(const char *label, float radius1, float radius2, float thickness, const ImColor &color1 = white, const ImColor &color2 = red, float speed = 2.8f, float angle = IM_PI, int mode = 0)
  attach_function :SpinnerTwinAng,   [:string, :float, :float, :float], :void
  attach_function :SpinnerTwinAngEx, [:string, :float, :float, :float, :pointer, :pointer, :float, :float, :int], :void

# [ 35] C++ definition
#     void Spinner::SpinnerFilling(const char *label, float radius, float thickness, const ImColor &color1 = white, const ImColor &color2 = red, float speed = 2.8f)
  attach_function :SpinnerFilling,   [:string, :float, :float], :void
  attach_function :SpinnerFillingEx, [:string, :float, :float, :pointer, :pointer, :float], :void

# [ 36] C++ definition
#     void Spinner::SpinnerFillingMem(const char *label, float radius, float thickness, const ImColor &color, ImColor &colorbg, float speed)
  attach_function :SpinnerFillingMem,   [:string, :float, :float, :pointer, :pointer, :float], :void

# [ 37] C++ definition
#     void Spinner::SpinnerTopup(const char *label, float radius1, float radius2, const ImColor &color = red, const ImColor &fg = white, const ImColor &bg = white, float speed = 2.8f)
  attach_function :SpinnerTopup,   [:string, :float, :float], :void
  attach_function :SpinnerTopupEx, [:string, :float, :float, :pointer, :pointer, :pointer, :float], :void

# [ 38] C++ definition
#     void Spinner::SpinnerTwinAng180(const char *label, float radius1, float radius2, float thickness, const ImColor &color1 = white, const ImColor &color2 = red, float speed = 2.8f, float angle = PI_DIV_4, int mode = 0)
  attach_function :SpinnerTwinAng180,   [:string, :float, :float, :float], :void
  attach_function :SpinnerTwinAng180Ex, [:string, :float, :float, :float, :pointer, :pointer, :float, :float, :int], :void

# [ 39] C++ definition
#     void Spinner::SpinnerTwinAng360(const char *label, float radius1, float radius2, float thickness, const ImColor &color1 = white, const ImColor &color2 = red, float speed1 = 2.8f, float speed2 = 2.5f, int mode = 0)
  attach_function :SpinnerTwinAng360,   [:string, :float, :float, :float], :void
  attach_function :SpinnerTwinAng360Ex, [:string, :float, :float, :float, :pointer, :pointer, :float, :float, :int], :void

# [ 40] C++ definition
#     void Spinner::SpinnerIncDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 6)
  attach_function :SpinnerIncDots,   [:string, :float, :float], :void
  attach_function :SpinnerIncDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 41] C++ definition
#     void Spinner::SpinnerIncFullDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 4)
  attach_function :SpinnerIncFullDots,   [:string, :float, :float], :void
  attach_function :SpinnerIncFullDotsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 42] C++ definition
#     void Spinner::SpinnerFadeBars(const char *label, float w, const ImColor &color = white, float speed = 2.8f, size_t bars = 3, bool scale = false)
  attach_function :SpinnerFadeBars,   [:string, :float], :void
  attach_function :SpinnerFadeBarsEx, [:string, :float, :pointer, :float, :int, :bool], :void

# [ 43] C++ definition
#     void Spinner::SpinnerFadeTris(const char *label, float radius, const ImColor &color = white, float speed = 2.8f, size_t dim = 2, bool scale = false, int mode = 0)
  attach_function :SpinnerFadeTris,   [:string, :float], :void
  attach_function :SpinnerFadeTrisEx, [:string, :float, :pointer, :float, :int, :bool, :int], :void

# [ 44] C++ definition
#     void Spinner::SpinnerBarsRotateFade(const char *label, float rmin, float rmax , float thickness, const ImColor &color = white, float speed = 2.8f, size_t bars = 6)
  attach_function :SpinnerBarsRotateFade,   [:string, :float, :float, :float], :void
  attach_function :SpinnerBarsRotateFadeEx, [:string, :float, :float, :float, :pointer, :float, :int], :void

# [ 45] C++ definition
#     void Spinner::SpinnerBarsScaleMiddle(const char *label, float w, const ImColor &color = white, float speed = 2.8f, size_t bars = 3)
  attach_function :SpinnerBarsScaleMiddle,   [:string, :float], :void
  attach_function :SpinnerBarsScaleMiddleEx, [:string, :float, :pointer, :float, :int], :void

# [ 46] C++ definition
#     void Spinner::SpinnerAngTwin(const char *label, float radius1, float radius2, float thickness, const ImColor &color = white, const ImColor &bg = half_white, float speed = 2.8f, float angle = IM_PI, size_t arcs = 1, int mode = 0)
  attach_function :SpinnerAngTwin,   [:string, :float, :float, :float], :void
  attach_function :SpinnerAngTwinEx, [:string, :float, :float, :float, :pointer, :pointer, :float, :float, :int, :int], :void

# [ 47] C++ definition
#     void Spinner::SpinnerArcRotation(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t arcs = 4, int mode = 0)
  attach_function :SpinnerArcRotation,   [:string, :float, :float], :void
  attach_function :SpinnerArcRotationEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 48] C++ definition
#     void Spinner::SpinnerArcFade(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t arcs = 4, int mode = 0)
  attach_function :SpinnerArcFade,   [:string, :float, :float], :void
  attach_function :SpinnerArcFadeEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 49] C++ definition
#     void Spinner::SpinnerSimpleArcFade(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerSimpleArcFade,   [:string, :float, :float], :void
  attach_function :SpinnerSimpleArcFadeEx, [:string, :float, :float, :pointer, :float], :void

# [ 50] C++ definition
#     void Spinner::SpinnerSquareStrokeFade(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerSquareStrokeFade,   [:string, :float, :float], :void
  attach_function :SpinnerSquareStrokeFadeEx, [:string, :float, :float, :pointer, :float], :void

# [ 51] C++ definition
#     void Spinner::SpinnerAsciiSymbolPoints(const char *label, const char* text, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerAsciiSymbolPoints,   [:string, :string, :float, :float], :void
  attach_function :SpinnerAsciiSymbolPointsEx, [:string, :string, :float, :float, :pointer, :float], :void

# [ 52] C++ definition
#     void Spinner::SpinnerTextFading(const char *label, const char* text, float radius, float fsize, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerTextFading,   [:string, :string, :float, :float], :void
  attach_function :SpinnerTextFadingEx, [:string, :string, :float, :float, :pointer, :float], :void

# [ 53] C++ definition
#     void Spinner::SpinnerSevenSegments(const char *label, const char* text, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerSevenSegments,   [:string, :string, :float, :float], :void
  attach_function :SpinnerSevenSegmentsEx, [:string, :string, :float, :float, :pointer, :float], :void

# [ 54] C++ definition
#     void Spinner::SpinnerSquareStrokeFill(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerSquareStrokeFill,   [:string, :float, :float], :void
  attach_function :SpinnerSquareStrokeFillEx, [:string, :float, :float, :pointer, :float], :void

# [ 55] C++ definition
#     void Spinner::SpinnerSquareStrokeLoading(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerSquareStrokeLoading,   [:string, :float, :float], :void
  attach_function :SpinnerSquareStrokeLoadingEx, [:string, :float, :float, :pointer, :float], :void

# [ 56] C++ definition
#     void Spinner::SpinnerSquareLoading(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerSquareLoading,   [:string, :float, :float], :void
  attach_function :SpinnerSquareLoadingEx, [:string, :float, :float, :pointer, :float], :void

# [ 57] C++ definition
#     void Spinner::SpinnerFilledArcFade(const char *label, float radius, const ImColor &color = white, float speed = 2.8f, size_t arcs = 4, int mode = 0)
  attach_function :SpinnerFilledArcFade,   [:string, :float], :void
  attach_function :SpinnerFilledArcFadeEx, [:string, :float, :pointer, :float, :int, :int], :void

# [ 58] C++ definition
#     void Spinner::SpinnerPointsRoller(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t points = 8, int circles = 2, float rspeed = 1.f)
  attach_function :SpinnerPointsRoller,   [:string, :float, :float], :void
  attach_function :SpinnerPointsRollerEx, [:string, :float, :float, :pointer, :float, :int, :int, :float], :void

# [ 59] C++ definition
#     void Spinner::SpinnerPointsArcBounce(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t points = 4, int circles = 2, float rspeed = 0.f)
  attach_function :SpinnerPointsArcBounce,   [:string, :float, :float], :void
  attach_function :SpinnerPointsArcBounceEx, [:string, :float, :float, :pointer, :float, :int, :int, :float], :void

# [ 60] C++ definition
#     void Spinner::SpinnerFilledArcColor(const char *label, float radius, const ImColor &color = red, const ImColor &bg = white, float speed = 2.8f, size_t arcs = 4)
  attach_function :SpinnerFilledArcColor,   [:string, :float], :void
  attach_function :SpinnerFilledArcColorEx, [:string, :float, :pointer, :pointer, :float, :int], :void

# [ 61] C++ definition
#     void Spinner::SpinnerFilledArcRing(const char *label, float radius, float thickness, const ImColor &color = red, const ImColor &bg = white, float speed = 2.8f, size_t arcs = 4)
  attach_function :SpinnerFilledArcRing,   [:string, :float, :float], :void
  attach_function :SpinnerFilledArcRingEx, [:string, :float, :float, :pointer, :pointer, :float, :int], :void

# [ 62] C++ definition
#     void Spinner::SpinnerArcWedges(const char *label, float radius, const ImColor &color = red, float speed = 2.8f, size_t arcs = 4, int mode = 0)
  attach_function :SpinnerArcWedges,   [:string, :float], :void
  attach_function :SpinnerArcWedgesEx, [:string, :float, :pointer, :float, :int, :int], :void

# [ 63] C++ definition
#     void Spinner::SpinnerTwinBall(const char *label, float radius1, float radius2, float thickness, float b_thickness, const ImColor &ball = white, const ImColor &bg = half_white, float speed = 2.8f, size_t balls = 2, int mode = 0)
  attach_function :SpinnerTwinBall,   [:string, :float, :float, :float, :float], :void
  attach_function :SpinnerTwinBallEx, [:string, :float, :float, :float, :float, :pointer, :pointer, :float, :int, :int], :void

# [ 64] C++ definition
#     void Spinner::SpinnerSolarBalls(const char *label, float radius, float thickness, const ImColor &ball = white, const ImColor &bg = half_white, float speed = 2.8f, size_t balls = 4)
  attach_function :SpinnerSolarBalls,   [:string, :float, :float], :void
  attach_function :SpinnerSolarBallsEx, [:string, :float, :float, :pointer, :pointer, :float, :int], :void

# [ 65] C++ definition
#     void Spinner::SpinnerSolarScaleBalls(const char *label, float radius, float thickness, const ImColor &ball = white, float speed = 2.8f, size_t balls = 4)
  attach_function :SpinnerSolarScaleBalls,   [:string, :float, :float], :void
  attach_function :SpinnerSolarScaleBallsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 66] C++ definition
#     void Spinner::SpinnerSolarArcs(const char *label, float radius, float thickness, const ImColor &ball = white, const ImColor &bg = half_white, float speed = 2.8f, size_t balls = 4)
  attach_function :SpinnerSolarArcs,   [:string, :float, :float], :void
  attach_function :SpinnerSolarArcsEx, [:string, :float, :float, :pointer, :pointer, :float, :int], :void

# [ 67] C++ definition
#     void Spinner::SpinnerMovingArcs(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t arcs = 4)
  attach_function :SpinnerMovingArcs,   [:string, :float, :float], :void
  attach_function :SpinnerMovingArcsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 68] C++ definition
#     void Spinner::SpinnerRainbowCircle(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t arcs = 4, float mode = 1)
  attach_function :SpinnerRainbowCircle,   [:string, :float, :float], :void
  attach_function :SpinnerRainbowCircleEx, [:string, :float, :float, :pointer, :float, :int, :float], :void

# [ 69] C++ definition
#     void Spinner::SpinnerBounceBall(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int dots = 1, bool shadow = false)
  attach_function :SpinnerBounceBall,   [:string, :float, :float], :void
  attach_function :SpinnerBounceBallEx, [:string, :float, :float, :pointer, :float, :int, :bool], :void

# [ 70] C++ definition
#     void Spinner::SpinnerPulsarBall(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, bool shadow = false, int mode = 0)
  attach_function :SpinnerPulsarBall,   [:string, :float, :float], :void
  attach_function :SpinnerPulsarBallEx, [:string, :float, :float, :pointer, :float, :bool, :int], :void

# [ 71] C++ definition
#     void Spinner::SpinnerIncScaleDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 6, float angle = 0.f, int mode = 0)
  attach_function :SpinnerIncScaleDots,   [:string, :float, :float], :void
  attach_function :SpinnerIncScaleDotsEx, [:string, :float, :float, :pointer, :float, :int, :float, :int], :void

# [ 72] C++ definition
#     void Spinner::SpinnerSomeScaleDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t dots = 6, int mode = 0)
  attach_function :SpinnerSomeScaleDots,   [:string, :float, :float], :void
  attach_function :SpinnerSomeScaleDotsEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 73] C++ definition
#     void Spinner::SpinnerAngTriple(const char *label, float radius1, float radius2, float radius3, float thickness, const ImColor &c1 = white, const ImColor &c2 = half_white, const ImColor &c3 = white, float speed = 2.8f, float angle = IM_PI)
  attach_function :SpinnerAngTriple,   [:string, :float, :float, :float, :float], :void
  attach_function :SpinnerAngTripleEx, [:string, :float, :float, :float, :float, :pointer, :pointer, :pointer, :float, :float], :void

# [ 74] C++ definition
#     void Spinner::SpinnerAngEclipse(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, float angle = IM_PI)
  attach_function :SpinnerAngEclipse,   [:string, :float, :float], :void
  attach_function :SpinnerAngEclipseEx, [:string, :float, :float, :pointer, :float, :float], :void

# [ 75] C++ definition
#     void Spinner::SpinnerIngYang(const char *label, float radius, float thickness, bool reverse, float yang_detlta_r, const ImColor &colorI = white, const ImColor &colorY = white, float speed = 2.8f, float angle = IM_PI * 0.7f, int mode = 0)
  attach_function :SpinnerIngYang,   [:string, :float, :float, :bool, :float], :void
  attach_function :SpinnerIngYangEx, [:string, :float, :float, :bool, :float, :pointer, :pointer, :float, :float, :int], :void

# [ 76] C++ definition
#     void Spinner::SpinnerGooeyBalls(const char *label, float radius, const ImColor &color, float speed, int mode = 0)
  attach_function :SpinnerGooeyBalls,   [:string, :float, :pointer, :float], :void
  attach_function :SpinnerGooeyBallsEx, [:string, :float, :pointer, :float, :int], :void

# [ 77] C++ definition
#     void Spinner::SpinnerDotsLoading(const char *label, float radius, float thickness, const ImColor &color, const ImColor &bg, float speed)
  attach_function :SpinnerDotsLoading,   [:string, :float, :float, :pointer, :pointer, :float], :void

# [ 78] C++ definition
#     void Spinner::SpinnerRotateGooeyBalls(const char *label, float radius, float thickness, const ImColor &color, float speed, int balls, int mode = 0)
  attach_function :SpinnerRotateGooeyBalls,   [:string, :float, :float, :pointer, :float, :int], :void
  attach_function :SpinnerRotateGooeyBallsEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 79] C++ definition
#     void Spinner::SpinnerHerbertBalls(const char *label, float radius, float thickness, const ImColor &color, float speed, int balls)
  attach_function :SpinnerHerbertBalls,   [:string, :float, :float, :pointer, :float, :int], :void

# [ 80] C++ definition
#     void Spinner::SpinnerHerbertBalls3D(const char *label, float radius, float thickness, const ImColor &color, float speed)
  attach_function :SpinnerHerbertBalls3D,   [:string, :float, :float, :pointer, :float], :void

# [ 81] C++ definition
#     void Spinner::SpinnerRotateTriangles(const char *label, float radius, float thickness, const ImColor &color, float speed, int tris, int mode = 0)
  attach_function :SpinnerRotateTriangles,   [:string, :float, :float, :pointer, :float, :int], :void
  attach_function :SpinnerRotateTrianglesEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 82] C++ definition
#     void Spinner::SpinnerRotateShapes(const char *label, float radius, float thickness, const ImColor &color, float speed, int shapes, int pnt)
  attach_function :SpinnerRotateShapes,   [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 83] C++ definition
#     void Spinner::SpinnerSinSquares(const char *label, float radius, float thickness, const ImColor &color, float speed, int mode = 0)
  attach_function :SpinnerSinSquares,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerSinSquaresEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 84] C++ definition
#     void Spinner::SpinnerMoonLine(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = red, float speed = 2.8f, float angle = IM_PI)
  attach_function :SpinnerMoonLine,   [:string, :float, :float], :void
  attach_function :SpinnerMoonLineEx, [:string, :float, :float, :pointer, :pointer, :float, :float], :void

# [ 85] C++ definition
#     void Spinner::SpinnerCircleDrop(const char *label, float radius, float thickness, float thickness_drop, const ImColor &color = white, const ImColor &bg = half_white, float speed = 2.8f, float angle = IM_PI)
  attach_function :SpinnerCircleDrop,   [:string, :float, :float, :float], :void
  attach_function :SpinnerCircleDropEx, [:string, :float, :float, :float, :pointer, :pointer, :float, :float], :void

# [ 86] C++ definition
#     void Spinner::SpinnerSurroundedIndicator(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = half_white, float speed = 2.8f)
  attach_function :SpinnerSurroundedIndicator,   [:string, :float, :float], :void
  attach_function :SpinnerSurroundedIndicatorEx, [:string, :float, :float, :pointer, :pointer, :float], :void

# [ 87] C++ definition
#     void Spinner::SpinnerWifiIndicator(const char *label, float radius, float thickness, const ImColor &color = red, const ImColor &bg = half_white, float speed = 2.8f, float cangle = 0.f, int dots = 3)
  attach_function :SpinnerWifiIndicator,   [:string, :float, :float], :void
  attach_function :SpinnerWifiIndicatorEx, [:string, :float, :float, :pointer, :pointer, :float, :float, :int], :void

# [ 88] C++ definition
#     void Spinner::SpinnerTrianglesSelector(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = half_white, float speed = 2.8f, size_t bars = 8)
  attach_function :SpinnerTrianglesSelector,   [:string, :float, :float], :void
  attach_function :SpinnerTrianglesSelectorEx, [:string, :float, :float, :pointer, :pointer, :float, :int], :void

# [ 89] C++ definition
#     void Spinner::SpinnerCamera(const char *label, float radius, float thickness, LeafColor *leaf_color, float speed = 2.8f, size_t bars = 8, int mode = 0)
  attach_function :SpinnerCamera,   [:string, :float, :float, :pointer], :void
  attach_function :SpinnerCameraEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [ 90] C++ definition
#     void Spinner::SpinnerFlowingGradient(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = red, float speed = 2.8f, float angle = IM_PI)
  attach_function :SpinnerFlowingGradient,   [:string, :float, :float], :void
  attach_function :SpinnerFlowingGradientEx, [:string, :float, :float, :pointer, :pointer, :float, :float], :void

# [ 91] C++ definition
#     void Spinner::SpinnerRotateSegments(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t arcs = 4, size_t layers = 1, int mode = 0)
  attach_function :SpinnerRotateSegments,   [:string, :float, :float], :void
  attach_function :SpinnerRotateSegmentsEx, [:string, :float, :float, :pointer, :float, :int, :int, :int], :void

# [ 92] C++ definition
#     void Spinner::SpinnerLemniscate(const char* label, float radius, float thickness, const ImColor& color = white, float speed = 2.8f, float angle = IM_PI / 2.0f)
  attach_function :SpinnerLemniscate,   [:string, :float, :float], :void
  attach_function :SpinnerLemniscateEx, [:string, :float, :float, :pointer, :float, :float], :void

# [ 93] C++ definition
#     void Spinner::SpinnerRotateGear(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t pins = 12)
  attach_function :SpinnerRotateGear,   [:string, :float, :float], :void
  attach_function :SpinnerRotateGearEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 94] C++ definition
#     void Spinner::SpinnerRotateWheel(const char *label, float radius, float thickness, const ImColor &bg_color = white, const ImColor &color = white, float speed = 2.8f, size_t pins = 12)
  attach_function :SpinnerRotateWheel,   [:string, :float, :float], :void
  attach_function :SpinnerRotateWheelEx, [:string, :float, :float, :pointer, :pointer, :float, :int], :void

# [ 95] C++ definition
#     void Spinner::SpinnerAtom(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int elipses = 3)
  attach_function :SpinnerAtom,   [:string, :float, :float], :void
  attach_function :SpinnerAtomEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 96] C++ definition
#     void Spinner::SpinnerPatternRings(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int elipses = 3)
  attach_function :SpinnerPatternRings,   [:string, :float, :float], :void
  attach_function :SpinnerPatternRingsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 97] C++ definition
#     void Spinner::SpinnerPatternEclipse(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int elipses = 3, float delta_a = 2.f, float delta_y = 0.f)
  attach_function :SpinnerPatternEclipse,   [:string, :float, :float], :void
  attach_function :SpinnerPatternEclipseEx, [:string, :float, :float, :pointer, :float, :int, :float, :float], :void

# [ 98] C++ definition
#     void Spinner::SpinnerPatternSphere(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int elipses = 3)
  attach_function :SpinnerPatternSphere,   [:string, :float, :float], :void
  attach_function :SpinnerPatternSphereEx, [:string, :float, :float, :pointer, :float, :int], :void

# [ 99] C++ definition
#     void Spinner::SpinnerRingSynchronous(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int elipses = 3)
  attach_function :SpinnerRingSynchronous,   [:string, :float, :float], :void
  attach_function :SpinnerRingSynchronousEx, [:string, :float, :float, :pointer, :float, :int], :void

# [100] C++ definition
#     void Spinner::SpinnerRingWatermarks(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int elipses = 3)
  attach_function :SpinnerRingWatermarks,   [:string, :float, :float], :void
  attach_function :SpinnerRingWatermarksEx, [:string, :float, :float, :pointer, :float, :int], :void

# [101] C++ definition
#     void Spinner::SpinnerRotatedAtom(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int elipses = 3, int mode = 0)
  attach_function :SpinnerRotatedAtom,   [:string, :float, :float], :void
  attach_function :SpinnerRotatedAtomEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [102] C++ definition
#     void Spinner::SpinnerRainbowBalls(const char *label, float radius, float thickness, const ImColor &color, float speed, int balls = 5, int mode = 0, int rings = 1, int mx = 1)
  attach_function :SpinnerRainbowBalls,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerRainbowBallsEx, [:string, :float, :float, :pointer, :float, :int, :int, :int, :int], :void

# [103] C++ definition
#     void Spinner::SpinnerRainbowShot(const char *label, float radius, float thickness, const ImColor &color, float speed, int balls = 5, int mode = 0)
  attach_function :SpinnerRainbowShot,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerRainbowShotEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [104] C++ definition
#     void Spinner::SpinnerSpiral(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t arcs = 4)
  attach_function :SpinnerSpiral,   [:string, :float, :float], :void
  attach_function :SpinnerSpiralEx, [:string, :float, :float, :pointer, :float, :int], :void

# [105] C++ definition
#     void Spinner::SpinnerSpiralEye(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerSpiralEye,   [:string, :float, :float], :void
  attach_function :SpinnerSpiralEyeEx, [:string, :float, :float, :pointer, :float], :void

# [106] C++ definition
#     void Spinner::SpinnerBarChartSine(const char *label, float radius, float thickness, const ImColor &color, float speed, int bars = 5, int mode = 0)
  attach_function :SpinnerBarChartSine,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerBarChartSineEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [107] C++ definition
#     void Spinner::SpinnerBarChartAdvSine(const char *label, float radius, float thickness, const ImColor &color, float speed, int mode = 0)
  attach_function :SpinnerBarChartAdvSine,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerBarChartAdvSineEx, [:string, :float, :float, :pointer, :float, :int], :void

# [108] C++ definition
#     void Spinner::SpinnerBarChartAdvSineFade(const char *label, float radius, float thickness, const ImColor &color, float speed, int mode = 0)
  attach_function :SpinnerBarChartAdvSineFade,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerBarChartAdvSineFadeEx, [:string, :float, :float, :pointer, :float, :int], :void

# [109] C++ definition
#     void Spinner::SpinnerBarChartRainbow(const char *label, float radius, float thickness, const ImColor &color, float speed, int bars = 5, int mode = 0)
  attach_function :SpinnerBarChartRainbow,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerBarChartRainbowEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [110] C++ definition
#     void Spinner::SpinnerBlocks(const char *label, float radius, float thickness, const ImColor &bg, const ImColor &color, float speed)
  attach_function :SpinnerBlocks,   [:string, :float, :float, :pointer, :pointer, :float], :void

# [111] C++ definition
#     void Spinner::SpinnerTwinBlocks(const char *label, float radius, float thickness, const ImColor &bg, const ImColor &color, float speed)
  attach_function :SpinnerTwinBlocks,   [:string, :float, :float, :pointer, :pointer, :float], :void

# [112] C++ definition
#     void Spinner::SpinnerSquareRandomDots(const char *label, float radius, float thickness, const ImColor &bg, const ImColor &color, float speed)
  attach_function :SpinnerSquareRandomDots,   [:string, :float, :float, :pointer, :pointer, :float], :void

# [113] C++ definition
#     void Spinner::SpinnerScaleBlocks(const char *label, float radius, float thickness, const ImColor &color, float speed, int mode = 0)
  attach_function :SpinnerScaleBlocks,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerScaleBlocksEx, [:string, :float, :float, :pointer, :float, :int], :void

# [114] C++ definition
#     void Spinner::SpinnerScaleSquares(const char *label, float radius, float thikness, const ImColor &color, float speed)
  attach_function :SpinnerScaleSquares,   [:string, :float, :float, :pointer, :float], :void

# [115] C++ definition
#     void Spinner::SpinnerSquishSquare(const char *label, float radius, const ImColor &color, float speed)
  attach_function :SpinnerSquishSquare,   [:string, :float, :pointer, :float], :void

# [116] C++ definition
#     void Spinner::SpinnerFluid(const char *label, float radius, const ImColor &color, float speed, int bars = 3)
  attach_function :SpinnerFluid,   [:string, :float, :pointer, :float], :void
  attach_function :SpinnerFluidEx, [:string, :float, :pointer, :float, :int], :void

# [117] C++ definition
#     void Spinner::SpinnerFluidPoints(const char *label, float radius, float thickness, const ImColor &color, float speed, size_t dots = 6, float delta = 0.35f)
  attach_function :SpinnerFluidPoints,   [:string, :float, :float, :pointer, :float], :void
  attach_function :SpinnerFluidPointsEx, [:string, :float, :float, :pointer, :float, :int, :float], :void

# [118] C++ definition
#     void Spinner::SpinnerArcPolarFade(const char *label, float radius, const ImColor &color = white, float speed = 2.8f, size_t arcs = 4, int mode = 0)
  attach_function :SpinnerArcPolarFade,   [:string, :float], :void
  attach_function :SpinnerArcPolarFadeEx, [:string, :float, :pointer, :float, :int, :int], :void

# [119] C++ definition
#     void Spinner::SpinnerArcPolarRadius(const char *label, float radius, const ImColor &color = white, float speed = 2.8f, size_t arcs = 4, int mode = 0)
  attach_function :SpinnerArcPolarRadius,   [:string, :float], :void
  attach_function :SpinnerArcPolarRadiusEx, [:string, :float, :pointer, :float, :int, :int], :void

# [120] C++ definition
#     void Spinner::SpinnerCaleidoscope(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t arcs = 6, int mode = 0)
  attach_function :SpinnerCaleidoscope,   [:string, :float, :float], :void
  attach_function :SpinnerCaleidoscopeEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [121] C++ definition
#     void Spinner::SpinnerHboDots(const char *label, float radius, float thickness, const ImColor &color = white, float minfade = 0.0f, float ryk = 0.f, float speed = 1.1f, size_t dots = 6, int mode = 0)
  attach_function :SpinnerHboDots,   [:string, :float, :float], :void
  attach_function :SpinnerHboDotsEx, [:string, :float, :float, :pointer, :float, :float, :float, :int, :int], :void

# [122] C++ definition
#     void Spinner::SpinnerMoonDots(const char *label, float radius, float thickness, const ImColor &first, const ImColor &second, float speed = 1.1f)
  attach_function :SpinnerMoonDots,   [:string, :float, :float, :pointer, :pointer], :void
  attach_function :SpinnerMoonDotsEx, [:string, :float, :float, :pointer, :pointer, :float], :void

# [123] C++ definition
#     void Spinner::SpinnerTwinHboDots(const char *label, float radius, float thickness, const ImColor &color = white, float minfade = 0.0f, float ryk = 0.f, float speed = 1.1f, size_t dots = 6, float delta = 0.f)
  attach_function :SpinnerTwinHboDots,   [:string, :float, :float], :void
  attach_function :SpinnerTwinHboDotsEx, [:string, :float, :float, :pointer, :float, :float, :float, :int, :float], :void

# [124] C++ definition
#     void Spinner::SpinnerThreeDotsStar(const char *label, float radius, float thickness, const ImColor &color = white, float minfade = 0.0f, float ryk = 0.f, float speed = 1.1f, float delta = 0.f)
  attach_function :SpinnerThreeDotsStar,   [:string, :float, :float], :void
  attach_function :SpinnerThreeDotsStarEx, [:string, :float, :float, :pointer, :float, :float, :float, :float], :void

# [125] C++ definition
#     void Spinner::SpinnerSineArcs(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerSineArcs,   [:string, :float, :float], :void
  attach_function :SpinnerSineArcsEx, [:string, :float, :float, :pointer, :float], :void

# [126] C++ definition
#     void Spinner::SpinnerTrianglesShift(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = half_white, float speed = 2.8f, size_t bars = 8)
  attach_function :SpinnerTrianglesShift,   [:string, :float, :float], :void
  attach_function :SpinnerTrianglesShiftEx, [:string, :float, :float, :pointer, :pointer, :float, :int], :void

# [127] C++ definition
#     void Spinner::SpinnerPointsShift(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = half_white, float speed = 2.8f, size_t bars = 8)
  attach_function :SpinnerPointsShift,   [:string, :float, :float], :void
  attach_function :SpinnerPointsShiftEx, [:string, :float, :float, :pointer, :pointer, :float, :int], :void

# [128] C++ definition
#     void Spinner::SpinnerSwingDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f)
  attach_function :SpinnerSwingDots,   [:string, :float, :float], :void
  attach_function :SpinnerSwingDotsEx, [:string, :float, :float, :pointer, :float], :void

# [129] C++ definition
#     void Spinner::SpinnerCircularPoints(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 1.8f, int lines = 8)
  attach_function :SpinnerCircularPoints,   [:string, :float, :float], :void
  attach_function :SpinnerCircularPointsEx, [:string, :float, :float, :pointer, :float, :int], :void

# [130] C++ definition
#     void Spinner::SpinnerCurvedCircle(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t circles = 1)
  attach_function :SpinnerCurvedCircle,   [:string, :float, :float], :void
  attach_function :SpinnerCurvedCircleEx, [:string, :float, :float, :pointer, :float, :int], :void

# [131] C++ definition
#     void Spinner::SpinnerModCircle(const char *label, float radius, float thickness, const ImColor &color = white, float ang_min = 1.f, float ang_max = 1.f, float speed = 2.8f)
  attach_function :SpinnerModCircle,   [:string, :float, :float], :void
  attach_function :SpinnerModCircleEx, [:string, :float, :float, :pointer, :float, :float, :float], :void

# [132] C++ definition
#     void Spinner::SpinnerDnaDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, int lt = 8, float delta = 0.5f, bool mode = 0)
  attach_function :SpinnerDnaDots,   [:string, :float, :float], :void
  attach_function :SpinnerDnaDotsEx, [:string, :float, :float, :pointer, :float, :int, :float, :bool], :void

# [133] C++ definition
#     void Spinner::Spinner3SmuggleDots(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 4.8f, int lt = 8, float delta = 0.5f, bool mode = 0)
  attach_function :Spinner3SmuggleDots,   [:string, :float, :float], :void
  attach_function :Spinner3SmuggleDotsEx, [:string, :float, :float, :pointer, :float, :int, :float, :bool], :void

# [134] C++ definition
#     void Spinner::SpinnerRotateSegmentsPulsar(const char *label, float radius, float thickness, const ImColor &color = white, float speed = 2.8f, size_t arcs = 4, size_t layers = 1)
  attach_function :SpinnerRotateSegmentsPulsar,   [:string, :float, :float], :void
  attach_function :SpinnerRotateSegmentsPulsarEx, [:string, :float, :float, :pointer, :float, :int, :int], :void

# [135] C++ definition
#     void Spinner::SpinnerSplineAng(const char *label, float radius, float thickness, const ImColor &color = white, const ImColor &bg = white, float speed = 2.8f, float angle = IM_PI, int mode = 0)
  attach_function :SpinnerSplineAng,   [:string, :float, :float], :void
  attach_function :SpinnerSplineAngEx, [:string, :float, :float, :pointer, :pointer, :float, :float, :int], :void

# ImSpnner demo
  attach_function :demoSpinners,[], :void
end
