name: rel_zip_win

on:
  push:
    tags:
      - 'v*'      # 例: v1.0.0
      - '[0-9]*'  # 例: 1.0.0, 2.1.3

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: "igruby_examples"
      OTHER_REPO: "ruby-imgui-dev"
      OTHER_REPO_OWNER: "dinau"

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run Makefile
        run: |
          make
        shell: bash

      - name: Download latest taged ruby-imgui-dev files
        run: |
          mkdir -p "${RUNNER_TEMP}/mytemp"
          pushd "${RUNNER_TEMP}/mytemp"
          #
          mkdir -p ${OTHER_REPO}/lib
          pushd ${OTHER_REPO}
          #
          echo "Fetching tags from https://api.github.com/repos/${OTHER_REPO_OWNER}/${OTHER_REPO}/tags"
          LATEST_TAG=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${OTHER_REPO_OWNER}/${OTHER_REPO}/tags | jq -r '.[0].name')
          echo "Download tag version ${OTHER_REPO}: ${LATEST_TAG}"
          #
          curl -L --fail -o  ChangeLog              https://raw.githubusercontent.com/${OTHER_REPO_OWNER}/${OTHER_REPO}/${LATEST_TAG}/ChangeLog
          curl -L --fail -o  LICENSE.txt            https://raw.githubusercontent.com/${OTHER_REPO_OWNER}/${OTHER_REPO}/${LATEST_TAG}/LICENSE.txt
          curl -L --fail -o  README.md              https://raw.githubusercontent.com/${OTHER_REPO_OWNER}/${OTHER_REPO}/${LATEST_TAG}/README.md
          curl -L --fail -o  imgui-bindings.gemspec https://raw.githubusercontent.com/${OTHER_REPO_OWNER}/${OTHER_REPO}/${LATEST_TAG}/imgui-bindings.gemspec
          curl -L --fail -o  lib/glfw3.dll          https://raw.githubusercontent.com/${OTHER_REPO_OWNER}/${OTHER_REPO}/${LATEST_TAG}/lib/glfw3.dll
          curl -L --fail -o  lib/imgui.dll          https://raw.githubusercontent.com/${OTHER_REPO_OWNER}/${OTHER_REPO}/${LATEST_TAG}/lib/imgui.dll
          curl -L --fail -o  lib/imgui.rb           https://raw.githubusercontent.com/${OTHER_REPO_OWNER}/${OTHER_REPO}/${LATEST_TAG}/lib/imgui.rb
          curl -L --fail -o  lib/imgui_internal.rb  https://raw.githubusercontent.com/${OTHER_REPO_OWNER}/${OTHER_REPO}/${LATEST_TAG}/lib/imgui_internal.rb
          #
          echo "Working in $(pwd)"
          popd  ### ${OTHER_REPO}
          tree
        shell: bash

      - name: Create release zip
        run: |
          zip -r "${REPO_NAME}.zip" . -x "*/.*"                                 # generate: ./igruby_example.zip
          unzip -o "${REPO_NAME}.zip" -d "${RUNNER_TEMP}/mytemp/${REPO_NAME}"
          #
          pushd "${RUNNER_TEMP}/mytemp"
          REF_NAME="${{ github.ref_name }}"                                     # Latest tag number of igruby_example
          RELEASE_ZIP_FILE="${REPO_NAME}-${REF_NAME}.zip"
          tree -d
          echo zip -r "${RELEASE_ZIP_FILE}" "${OTHER_REPO}" "${REPO_NAME}"
          zip      -r "${RELEASE_ZIP_FILE}" "${OTHER_REPO}" "${REPO_NAME}"
          #
          echo "RELEASE_ZIP_FILE=${RUNNER_TEMP}/mytemp/${RELEASE_ZIP_FILE}" >> $GITHUB_ENV
        shell: bash

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ env.RELEASE_ZIP_FILE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
